INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1001, 'Kunal', 'Get AWS Certified', CURRENT_DATE() , false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1002, 'Kunal', 'Learn Spring', CURRENT_DATE() , false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1003, 'Kunal', 'Learn React', CURRENT_DATE() , false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
values(1004, 'Kunal', 'Practice DSA', CURRENT_DATE() , false);